// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_1.Data;

#nullable disable

namespace Proyecto_1.Migrations
{
    [DbContext(typeof(SelvaDbContext))]
    [Migration("20251205035045_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_1.Models.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnimal"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoSalud")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdCuidador")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAnimal");

                    b.HasIndex("IdCuidador");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("Proyecto_1.Models.Cuidadores", b =>
                {
                    b.Property<int>("IdCuidadores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuidadores"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdCuidadores");

                    b.ToTable("Cuidadores");
                });

            modelBuilder.Entity("Proyecto_1.Models.MovimientoVisitas", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int?>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int>("IdCuidador")
                        .HasColumnType("int");

                    b.Property<int>("IdVisitante")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdAnimal");

                    b.HasIndex("IdCuidador");

                    b.HasIndex("IdVisitante");

                    b.ToTable("MovimientoVisitas");
                });

            modelBuilder.Entity("Proyecto_1.Models.Visitantes", b =>
                {
                    b.Property<int>("IdVisitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVisitante"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdVisitante");

                    b.ToTable("Visitantes");
                });

            modelBuilder.Entity("Proyecto_1.Models.Animal", b =>
                {
                    b.HasOne("Proyecto_1.Models.Cuidadores", "Cuidador")
                        .WithMany()
                        .HasForeignKey("IdCuidador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cuidador");
                });

            modelBuilder.Entity("Proyecto_1.Models.MovimientoVisitas", b =>
                {
                    b.HasOne("Proyecto_1.Models.Animal", "Animal")
                        .WithMany("MovimientoVisitas")
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_1.Models.Cuidadores", "Cuidador")
                        .WithMany()
                        .HasForeignKey("IdCuidador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_1.Models.Visitantes", "Visitante")
                        .WithMany("MovimientoVisitas")
                        .HasForeignKey("IdVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Cuidador");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Proyecto_1.Models.Animal", b =>
                {
                    b.Navigation("MovimientoVisitas");
                });

            modelBuilder.Entity("Proyecto_1.Models.Visitantes", b =>
                {
                    b.Navigation("MovimientoVisitas");
                });
#pragma warning restore 612, 618
        }
    }
}
